<?php

namespace app\admin\model;

class Node extends \think\Model {
    protected $table = 'node' ;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}