<?php

namespace app\admin\model;

class RoleNode extends \think\Model {
    protected $table = 'role_node';


    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}