<?php

namespace app\admin\model;

class Role extends \think\Model {
    protected $table = 'role';


    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}