<?php

namespace app\admin\model;

class UserRole extends  \think\Model {
    protected $table = 'user_role';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}