<?php

namespace app\admin\model;

class User extends \think\Model {
    protected $table = 'user';


    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}