<?php

namespace app\admin\controller;

use app\admin\model\Article;
use app\admin\model\Node;
use app\admin\model\Role;
use app\admin\model\User;

class Index extends \think\Controller {

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // TODO 自定义初始化
    }

    public function index() {
        $user = User::get(1);
        $role1 = Role::get(1);
        $role2 = Role::get(2);
        $node = Node::get(1);
        $dummy = '我是测试';
        return $this->fetch('index', ['user' => $user, 'role1' => $role1, 'role2' => $role2, 'node' => $node, 'dummy' => $dummy]);
    }

    public function signup() {
        return $this->fetch('signup', ["username" => ""]);
    }

    public function login() {
        return $this->fetch('login', ["username" => ""]);
    }

    public function logout() {
        return $this->fetch('index@index/index',["username" => ""]);
    }

    public function handleSignup($username, $phone, $passwd) {

        return $this->redirect("index/main_page/index", ["username" => $username]);
    }

    public function handleLogin($user, $passwd) {
        // 用户验证（用户名或手机号）
        $username = $user;
        return $this->redirect("index/main_page/index", ["username" => $username]);
    }
}