<?php

namespace app\admin\controller;

use app\admin\model\Article;
use app\admin\model\Node;
use app\admin\model\Role;
use app\admin\model\User;
use think\Session;

class Index extends \think\Controller {

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // TODO 自定义初始化
//        $user = new User([
//            'name'  =>  'Jobs',
//            'phone_number' =>  '13732253814',
//            'password' => '123456',
//            'register_time' => time(),
//        ]);
//        $user->save();
    }

    public function index() {

        $user = User::get(1);
//        $role1 = Role::get(1);
//        $role2 = Role::get(2);
//        $node = Node::get(1);
//        $dummy = '我是测试';
        $this->assign('username', '');
        return $this->fetch('index', ['user' => $user/*, 'role1' => $role1, 'role2' => $role2, 'node' => $node, 'dummy' => $dummy*/]);
    }

    public function signup() {
        return $this->fetch('signup');
    }

    public function login() {
        return $this->fetch('login');
    }

    public function logout() {
        Session::delete('username'); // session中的用户状态置为登出
        return $this->fetch('index@index/index');
    }

    public function handleSignup($username, $phone, $passwd) {
        $user = new User([
            'name' => $username,
            'phone_number' => $phone,
            'password' => $passwd,
            'register_time' => time(),
        ]);
        $user->save();
        Session::set('username', $username); // 注册成功之后状态直接变为登录
        return $this->redirect("index/main_page/index");
    }

    public function handleLogin($user, $passwd) {
        $username = $user;
        Session::set('username', $username);
        return $this->redirect("index/main_page/index");
    }
}