<?php
namespace app\common\exception\Http;

use Exception;
use think\exception\Handle;
use think\exception\HttpException;

// 自定义类需要继承Handle并且实现render方法，
class Http extends Handle {
    public function render(Exception $e)
    {
        if($e instanceof HttpException) {
            $statusCode = $e->getStatusCode();
        }

        // TODO 异常处理
        return parent::render($e); // TODO: Change the autogenerated stub
    }
}