<?php
namespace app\index\controller;

use app\index\model\Article;
use think\Request;

class Editor extends \think\Controller {
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function __construct(Request $request = null)
    {
        parent::__construct($request);
    }

    function index($id=-1, $username="") {
        $args['username'] = $username;
        if($id > 0) {
            $result = Article::get($id);
            if($result){
              //  array_merge($args, (array)$result);
                $args['id'] = $result['id'];
                $args['title'] = $result['title'];
                $args['content'] = $result['content'];
            }
        }

        return $this->fetch('index', ['username' => $username, 'args' => $args]);
    }

    function save($id=-1, $username="") {
        $content = $this->request->param('content');
        $title = $this->request->param('title');

        $art = new Article();
        if($id != -1) {
            $art->save(['content'=>$content, 'title' => $title], ['id' => $id]); // 更新
        } else {
            $art->save(['content'=>$content, 'title' => $title]); // 新增
        }

        $this->redirect('/index/main_page/index', ['username' => $username]);
    }

    function delete($id, $username="") {
        $art = Article::destroy($id);
        $res_json = json_encode(['status' => 0]);
        return $res_json;
    }
}
