<?php

namespace app\index\model;

class Article extends \think\Model {
    protected $table = 'article';


    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}